M1
digitalbazaar/bedrock-website-user-http pull request #1
Opened 2017-01-20 18:17 UTC by mattcollier

2017-01-20 18:19 UTC, mattcollier commented on lib/config.js
> +
I think these requires need to be in index.js.

2017-01-20 19:44 UTC, mattcollier commented
@dlongley ready for a look see.

2017-01-20 20:04 UTC, dlongley requested changes
AFAICT this looks ok functionality wise, just need a few tweaks to bring it up to speed on style.

2017-01-20 20:04 UTC, dlongley commented on lib/index.js
> +bedrock.events.on('bedrock-express.configure.routes', addRoutes);
Add `require('bedrock-express');` above.

2017-01-20 20:04 UTC, dlongley commented on lib/index.js
> +function addRoutes(app) {
Can probably just move this up and do: `app => {`

2017-01-20 20:04 UTC, dlongley commented on lib/index.js
> +      'bedrock.config.website-user-http.enableJoining to true');
Fix warning; has the wrong config var to change.

2017-01-20 20:04 UTC, dlongley commented on lib/index.js
> +        async.waterfall([
All of this could be ES6'd up. Also, use `async.auto` not `async.waterfall` for clarity.

2017-01-20 20:04 UTC, dlongley commented on lib/index.js
> +
Remove extra space.

2017-01-20 20:04 UTC, dlongley commented on lib/index.js
> +  var identityId = req.body.id;
`const` ... etc, I'm going to stop commenting on ES6 stuff -- just needs to be addressed in general.

2017-01-20 20:04 UTC, dlongley commented on lib/index.js
> +
Remove empty line.

2017-01-20 20:10 UTC, dlongley commented on lib/config.js
> +var path = require('path');
Should be `const`

2017-01-20 21:06 UTC, davidlehn commented on schemas/services.join.js
> +};
Could one-line this with ES2015:
```js
module.exports.postJoin = () => postJoin;
```

2017-01-20 21:30 UTC, mattcollier commented
@dlongley @davidlehn ready for another pass.

2017-01-20 22:25 UTC, dlongley commented on schemas/services.join.js
> +};
Why not just `module.exports.postJoin = postJoin;`?

2017-01-20 22:26 UTC, dlongley commented on schemas/services.join.js
> +};
The reason for it to be a function is to allow schema changes, but we don't even permit that here.

2017-01-25 02:18 UTC, dlongley approved these changes

2017-01-27 20:24 UTC, davidlehn approved these changes

2017-02-04 20:42 UTC, merged